Import libraries
Get some random data
Predict the output using some equation of type y=mx+b
Calculate errors
Calculate the sumof errors

In [1]:
import numpy as np

In [3]:
x = np.random.randint(-1, 5, 11) # generate 11 nos from -1 to 4
y_pred = 3*x + 2
print(y_pred) # got the predicted values using y=3x+2

[-1  5  8 14  5  2  8 -1 14  2  8]


In [5]:
# target value = 4
y = 4
error = abs(y_pred - y)
print(error)

[ 5  1  4 10  1  2  4  5 10  2  4]


In [7]:
error_sq =abs(y_pred - y)**2
print(error_sq)

[ 25   1  16 100   1   4  16  25 100   4  16]


In [9]:
print(error.sum()/11)
print(error_sq.sum()/11)

4.363636363636363
28.0
