In [ ]:
!pip install  tensorflow

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
# MAc - in terminal
pip install tensorflow 
Restart jupyter notebook

In [3]:
tf.__version__

'2.17.0'

In [5]:
# Create the rank 0 tensor
# tf.constant -> create a constant tensor 
rank0_tensor = tf.constant(4)
print(rank0_tensor) # Tensor object with value=4, empty shape, int32 dtype

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
# Create rank 1 tensor
rank1_tensor = tf.constant([2.0,4.0,5.0])
print(rank1_tensor) # tensor object values, shape 3, -> it has size 3 along first dimension, float dtype

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


In [11]:
# Create rank 2 tensor
rank2_tensor = tf.constant([[1,2],
                           [3,4],
                           [5,6]], dtype=tf.float64)
print(rank2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float64)


In [15]:
# create a rank 3 tensor
rank3_tensor = tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],
    [[10,11,12,13,14],
     [15,16,17,18,19]],
    [[20,21,22,23,24],
     [25,26,27,28,29]],])
print(rank3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [17]:
# basic mathematics on tensors 

a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[1,1],
                 [1,1]])
print(tf.add(a,b))
print()
print(tf.multiply(a,b))
print()
print(tf.matmul(a,b))  # matrix multiplication


tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [19]:
c = tf.constant([[4.0,5.0],[10.0,1.0]])
print(tf.reduce_max(c)) # calculate the maximum value in tensor c
print(tf.math.argmax(c)) # return the index of maximum value in Tensor c
print(tf.nn.softmax(c)) # apply the softmax activation function to ttensor c, 
                        # compute the probability distribution over the elemnets of c

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [30]:
x = tf.constant([1,2,3])
y = tf.constant(2)
z = tf.constant([2,2,2])
print(tf.multiply(x,2))
print(x*y)
print(x*z)
# Tensors - stretch automatically to fit the larger Tensors

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [32]:
# Ragged Tensor -> variable number of elements along some axes
ragged_list = [[0,1,2,3],
              [4,5],
              [6,7,8],
              [9]]
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [34]:
# Scalar String tensor - datatype, data can be represented as strings in Tensors
scalar_string_tensor = tf.constant("learning_tensors")
print(scalar_string_tensor)

tf.Tensor(b'learning_tensors', shape=(), dtype=string)


In [36]:
# Reshape Tensors
x = tf.constant([[1],[2],[3]])
print(x.shape)

(3, 1)


In [38]:
reshaped = tf.reshape(x, [1,3])
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)
